name: attendo
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  provider: ^4.3.2+2
#  fluttertoast: ^7.1.1
  firebase_core: ^0.5.0+1
  cloud_firestore: ^0.14.1+3
  google_sign_in: ^4.5.6
  firebase_auth: ^0.18.1+2
  flutter_local_notifications: ^1.4.4+2
  share: ^0.6.5+4
  uuid: ^2.2.2
  pdf: ^1.12.0
  path_provider: ^1.6.24
  flutter_full_pdf_viewer: ^1.0.6
  shared_preferences: ^0.5.12+4
  printing: ^3.7.1
  sleek_circular_slider: ^1.1.0



flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/artWork/
    - assets/images/others/

  fonts:
    - family: inter
      fonts:
        - asset: fonts/Inter-Black-slnt=0.ttf
        - asset: fonts/Inter-Bold-slnt=0.ttf
        - asset: fonts/Inter-ExtraBold-slnt=0.ttf
        - asset: fonts/Inter-ExtraLight-slnt=0.ttf
        - asset: fonts/Inter-Light-slnt=0.ttf
        - asset: fonts/Inter-Medium-slnt=0.ttf
        - asset: fonts/Inter-Regular-slnt=0.ttf
        - asset: fonts/Inter-SemiBold-slnt=0.ttf
        - asset: fonts/Inter-Thin-slnt=0.ttf
          style: italic


