name: attendo
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  provider: ^4.3.2+2
#  fluttertoast: ^7.1.1
  firebase_core: ^0.5.0+1
  cloud_firestore: ^0.14.1+3
  google_sign_in: ^4.5.6
  firebase_auth: ^0.18.1+2
  flutter_local_notifications: ^1.4.4+2
  share: ^0.6.5+4
  uuid: ^2.2.2
  pdf: ^1.12.0
  path_provider: ^1.6.24
  flutter_full_pdf_viewer: ^1.0.6


flutter:


  uses-material-design: true

  assets:
    - assets/images/artWork/
    - assets/images/others/



