import 'package:attendo/modals/list_of_course_details.dart';
import 'package:attendo/widgets/card_widget.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

//style
const bottomDrawerStyle =
TextStyle(color: Colors.black, fontSize: 20, fontWeight: FontWeight.bold);

///to join already created classes by others
class JoinNewClassScreen extends StatefulWidget {


  @override
  _JoinNewClassScreenState createState() => _JoinNewClassScreenState();
}

class _JoinNewClassScreenState extends State<JoinNewClassScreen> {

  String enteredClassCode;

  @override
  Widget build(BuildContext context) {
    return Container(
      color: Color(0xFF737373),
      child: Container(
        padding: EdgeInsets.all(20),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.only(
            topLeft: Radius.circular(20.0),
            topRight: Radius.circular(20.0),
          ),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Center(
              child: Text(
                'Join New Class',
                style: bottomDrawerStyle.copyWith(fontSize: 20),
              ),
            ),
            SizedBox(height: 8),
            Row(
              crossAxisAlignment: CrossAxisAlignment.baseline,
              textBaseline: TextBaseline.alphabetic,
              children: [
                Text(
                  'ClassCode :',
                  style: bottomDrawerStyle.copyWith(fontSize: 20),
                ),
                Expanded(
                  child: TextField(
                    onChanged: (String newValue){
                      enteredClassCode = newValue;
                    },
                    style: bottomDrawerStyle,
                    textAlign: TextAlign.center,
                    decoration: InputDecoration(
                      hintText: 'Enter Class Code',
                    ),
                  ),
                ),
              ],
            ),
            SizedBox(
              height: 5,
            ),
            Center(
              child: RaisedButton(
                onPressed: (){
                  //check if the entered code is in the List of Code generated by
                  //teachers previously, and if it matches, build the same courseCard
                  if(Provider.of<ListOfCourseDetails>(context, listen: false).listOfAllCourseCodes.contains(enteredClassCode))
                    {
                      //storing the index of courseCode and
                      int indexOfCode = Provider.of<ListOfCourseDetails>(context, listen: false).listOfAllCourseCodes.indexOf(enteredClassCode);
                      //storing that specific CardWidget to local Variable
                      CardWidget cardOfNewJoinClass=Provider.of<ListOfCourseDetails>(context, listen: false).finalListOfCreatedCourses[indexOfCode];
                      //and adding it to the NewListOfJoinedClasses
                      Provider.of<ListOfCourseDetails>(context, listen: false).addItemToJoinedCoursesList(cardOfNewJoinClass);

                    }
                  Navigator.pop(context);

                },
                child: Text(
                  'Create Class',
                  style: TextStyle(color: Colors.white),
                ),
                color: Colors.black,
              ),
            )
          ],
        ),
      ),
    );
  }
}
